### ISSUE TITLE
遇到首页无法显示标题的问题

### ISSUE THREAD

**Issue by acearth** [hueidou/hueidou.github.io#2]
http://acearth.github.io/LeetCodePractice/

在我保留您的文章在_post/中时，排版布局正常。
但在我删除掉您原有文章，并添加新文章后。目录没有显示出新增条目。而且排班也乱了。
怎么解决？ 
http://acearth.github.io/LeetCodePractice/

**Comment by acearth** [comment]
看了下index.html。 要从site.post中读取信息。 这里的site和url、baseurl有什么关系？ 

我将他们用于项目的github Pages， 需要怎么处理，求助。

**Comment by hueidou** [comment]
@acearth 样式文件/css/main.css加载失败，我见你是删掉了。

**Comment by acearth** [comment]
是删除了与main.css相关的文件？   main.css在的

**Comment by hueidou** [comment]
@acearth 哦，相对地址错了，因为你的站点是 http://acearth.github.io/ 下的LeetCodePractice目录，造成一些绝对地址的资源加载失败。

http://acearth.github.io/blog/css/main.css ，错误
http://acearth.github.io/LeetCodePractice/css/main.css

正确的做法是在config里设置你的baseurl为`/LeetCodePractice/`。

**Comment by acearth** [comment]
请问应该怎么设置， 不太熟。。。

2016-06-01 10:12 GMT+08:00 hueidou notifications@github.com:

**Comment by hueidou** [comment]
@acearth 我发了个PR，你merge就可以了：https://github.com/acearth/LeetCodePractice/pull/9

其实就是在`_config.yml`里把`baseurl`改为`/LeetCodePractice/`
